[tool.poetry]
name = "video-source-py"
version = "0.1.0"
description = "A generic video source extracting frames from any source OpenCV / ffmpeg supports and pushing it towards a consumer"
authors = ["flonix8 <flstanek@googlemail.com>"]
license = "GPL3"
readme = "README.md"
packages = [{include = "video_source_py"}]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^1.10.7"
opencv-python = "^4.7.0.72"
visionapi = { git = "https://github.com/starwit/vision-api.git", subdirectory = "python/visionapi", tag = "0.3.1" }


[tool.poetry.group.dev.dependencies]
jupyter = "^1.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
