id: video1
uri: /path/that/opencv/understands
# This sets a lower bound on frame times (i.e. frames are skipped)
# max_fps: 1
jpeg_encode: True
reconnect_backoff_time: 1
log_level: DEBUG
redis:
  host: redis-host
  port: 6379